import string
import secrets


def main():
    length = get_length()
    password = create_password(length)
    print(f"Your autogenerated password is: {password}")


def get_length():
    while True:
        try:
            l = int(input("Enter a password length between 8 and 20: "))
        except ValueError:
            print("You need to enter a valid digit!")
            continue
    
        if not 8 <= l <= 20:
            print("Length must be between 8 and 20.")
            continue

        return l


def create_password(l):
    characters = string.ascii_letters + string.digits + string.punctuation
    
    return "".join(secrets.choice(characters) for _ in range(l))


if __name__ == "__main__":
    main()